### ISSUE TITLE
Number of cycles being the goal and not the actual number of runs

### ISSUE THREAD

**Issue by H4ad** [yamiteru/isitfast#35]
When the benchmark is too slow, more cycles take too long, like this:

![image](https://user-images.githubusercontent.com/12551007/232325952-a7b86922-d3fe-4f0e-a224-b3cc5a6ad711.png)

I stopped after 11 minutes, but that could take a lot longer if I let it run.

Benchmark.js do something different, they aim for samples (cycles) but the amount of samples changes if the benchmark is slow, like this:

![image](https://user-images.githubusercontent.com/12551007/232326011-71d9f887-c632-4001-a995-a0afbf957905.png)

In case you wanna try:

- [object-hash.zip](https://github.com/yamiteru/isitfast/files/11242818/object-hash.zip)

**Comment by yamiteru** [comment]
Yeah I know about this. It looks like sometimes for some reason a very fast code is actually faster than an empty function which we use for offsets.

I don't want to target iterations/samples/cycles since I don't believe it's the right approach.

I guess we could cap the time spent collecting offsets to something like 10s. If it doesn't finish in that time then we just use smallest time minus 1ns as an offset.

**Comment by yamiteru** [comment]
Closing in favor of a bunch of new issues making this outdated.
