### ISSUE TITLE
CLI tool

### ISSUE THREAD

**Issue by H4ad** [yamiteru/isitfast#5]
One very annoying thing is when I need to show the benchmark, usually I put the code and the people who will run it need to install my benchmark package in the folder to be able to run the benchmark.

As I fork many packages, I even go so far as to create a bash function to run my benchmarks without having to install `benchmark.js` in the current folder.

It would be so nice if I could just post the code and people just create a file with it and then:

```bash
isitfast test-my-benchmark.js
```

The only downside is that it is difficult to pass node arguments like `--expose-gc` and other flags without needing to call the CLI directly with `node --expose-gc isitfast.js test-my-benchmark.js`.

The benchmarks could be defined like:

```
module.exports = {
  bench1: () => console.log('hey'),
  bench2: () => console.log('World'),
};
```

**Comment by H4ad** [comment]
In my libraries, I use [oclif](https://oclif.io/) to generate the boilerplate and deal with command and argument processing, the way they expose the functionalities is like this for linux:

```js
#!/usr/bin/env node

const oclif = require('@oclif/core')

oclif.run().then(require('@oclif/core/flush')).catch(require('@oclif/core/handle'))
```

What we can do instead is to keep as `#!/usr/bin/env`, then we process the flags and call node script with that flags.

Something like:

```bash
#!/usr/bin/env

$enable_gc="--expose-gc"

# some condition to disabled, I'm very bad at bash script

# I don't know either if this code compiles but I think you get the point
exec node $enable_gc linux_cli.js
# the content of linux_cli.js is the code above
``` 

For windows is even easier:

```powershell
@echo off

node "%~dp0\run" %*
```

Ref: [Linux](https://github.com/H4ad/tp-cli/blob/master/bin/run) and [Windows](https://github.com/H4ad/tp-cli/blob/master/bin/run.cmd)

**Comment by yamiteru** [comment]
That looks like a very solid solution. I'll try to piece something together. 

Thanks for pushing me into the right direction!

**Comment by H4ad** [comment]
I was thinking right now, if we push this feature, we can create a Github Action to integrate your benchmark, imagine create a lot of benchmarks like this:

- `bench/test-one.js`
- `bench/test-two.js`

And then, in the CI/CD, we just create something to run like:

```
- run: isitfast --filter bench/**.js
```

We can also push the results to a PR automatically, it will be insane to be used by libraries that want to add some performance tests.

I'm just throwing some ideas, you don't need to take it too much seriously hahahah

**Comment by yamiteru** [comment]
That sounds like fun! I'd like to integrate such benchmarks into [ts-package](https://github.com/yamiteru/ts-package) which is my template for libraries. I think it's much easier to just write a bunch of js/ts files that don't import anything than having to import the benchmark lib and set everything manually.

I'd like to make this way of using `isitfast` as modular as possible. We have to be able to:

## define options for each benchmark and/or for all benchmarks

I thing it can be solved in several ways. 

1. add flags like `--cpu-rangepercent`
2. add flag `--options` which would take path to JSON file
3. export `options` from individual benchmark files

I believe we can combine all of them together.

## subscribe to benchmark/suite events and/or do suite setup

I think when it comes to benchmark events we can do something like this:

```ts
// benchmarks/test.ts
export default {
  // optional suite name
  name: "Test",
  // benchmarks and their events 
  benchmarks: {
    "forEach": {
       benchmark: () => { /* */ },
       events: {
         beforeOne: () => { /* */ },
         afterAll: () => { /* */ }
       }
     }
  },
  // optional options
  options: {
    cpu: { rangePercent: 0.5 }
  }
};
```

I have to admit this is kind of verbose but I don't see any other way to do this. *Maybe* we could export those props (`name`/`benchmarks`/..) individually to make it a bit more cleaner.

One thing to keep in mind is that we lose TS types here. Let's say we also add `setup` prop just like `Suite.setup`. Then in all of the benchmarks we should be able to get the data generated from setup and see its correct type. With this approach it's impossible.

Another solution would be to force users to import the lib for non-trivial cases like these. But I'm not sure how I feel about that.

## use different modes for each/all benchmark file/s

I guess most of the users will want to use `useTerminalCompact` but what if in the future we add something like `useMarkdownCompact` which runs the benchmarks and saves the results into markdown?

So I guess we could add a flag `--mode` for that and/or export it from the file and/or embed the name of the mode in the name of the file like `array-loops.benchmark.terminal-compact.ts`.

**Comment by H4ad** [comment]
About options, I think you can start by exporting it from `benchmark` file and then add support to override by flags.

About the test file, you can organize like nextjs do:

```ts
export const options = {
    cpu: { rangePercent: 0.5 }  
};

export const firstSuite = {
  name: 'Test',
  benchmarks: {
    "forEach": {
       benchmark: () => { /* */ },
       events: {
         beforeOne: () => { /* */ },
         afterAll: () => { /* */ }
       }
     }
  },
};
```

In this way, I think could be a little better for readability.

About the TS Type, we could have if do like `nextjs` do, patching the global and exporting default interfaces, so we can use those interfaces in any file without importing `itisfast`.

The only thing that worries me is: how do we compile the TS files? Should we use `ts-node` to run the files if we detect that the benchmark file is `.ts`? `oclif` use `ts-node` like [this](https://github.com/H4ad/tp-cli/blob/master/bin/dev), essentially, if we use something like that, we could add a flag called `--tsconfig` to pass the config file for typescript, in this way, we can compile and run the files without problems.

About the mode, I really liked the behavior, having the option to export as markdown is a great thing because we can commit those files in the repository during the CI/CD phase and always have the updated benchmarks.

**Comment by yamiteru** [comment]
I agree with everything.

When it comes to `ts-node` I think we can use it instead of `node` since it can also run regular js files. No need for conditional logic based on file extension.

**Comment by yamiteru** [comment]
I'm making some really nice progress.

I run every benchmark file through esbuild. This way we can use different kinds of JS files like `ts`/`js`/`mjs`/`cjs`.

Also there are several ways we can define a benchmark:

1. `export default () => {}`
2. `export default { benchmark: () => {} }`
3. `export const benchmark = () => {}`

I've been thinking that when it comes to named exports we could prefix every benchmark with `$` since I could theoretically have an exported function named `benchmark` while also defining a benchmark for that function. So it should instead be `export const $benchmark = () => {}`.

This way we can easily support multiple benchmarks in the same file like this:

```ts
export const $for = () => {};

export const $while = () => {};

export const $forOf = () => {};

export const $forEach = () => {};
```

This is what I have so far:

<img width="579" alt="Screenshot 2023-04-28 at 9 12 25 PM" src="https://user-images.githubusercontent.com/34185465/235235132-a739b69a-df1d-4aea-b53d-0cdd4cde1a3c.png">

**Comment by yamiteru** [comment]
Oh and also as a part of this task I'm gonna implement #37.

Thanks to the on-the-fly compilation I can very easily create Workers like this:

```ts
const worker = new Worker(
    `
    const { parentPort } = require("node:worker_threads");

    (async () => {
      const fn = (await import("${outFile}")).${path};

      parentPort.on("message", ${prefix}() => {
        const start = ${capture};

        ${run};

        const end = ${capture};

        parentPort.postMessage(Number(end - start));
      });
    })();
  `,
    { eval: true },
  );
```

Since we precompute all function names, etc. the Worker code that measures the performance (the most important part in the whole library) has no unnecessary computations or allocations resulting in the least amount of noise.

**Comment by yamiteru** [comment]
Ok so all benchmarks in a file have to start with `$` and they have to be named exports. Default exports and named exports without the `$` prefix will be ignored (for now).

Now we can mangle files and folders together like this `isitfast one.ts two.js three/`. We go through all subfolders (theoretically infinitely) and gather all files and their benchmarks and after all folders have been scanned we then run all the benchmarks.

**Comment by yamiteru** [comment]
I'm currently wrestling with `SharedArrayBuffer`, `Uint32Array` and `Atomics`.

I was able to move all shared mutable data into one `Uint32Array` which should get rid of a tiny bit of memory noise.

Also I'm finding out that code runs a bit differently in Workers as opposed the main thread. This will require slight changes to the algorithm. On the main thread I saw smaller numbers and there was less deviations. It looks like NodeJS gives the main thread bigger priority when it comes to resource distribution. Also it seems like the speculative optimization process is less aggressive. Although all of this might be NodeJS specific and might not happen in other environments.

I'm also adding a bunch of new events that can give additional info about what's happening in the background.

I've also deleted a bunch of files and folder so the overall structure is much easier to understand and navigate.

There is one thing that I've been thinking about. It's very convenient to generate benchmarks on the fly. Something like this:

```ts
const suite = new Suite("Test");
const options = [ /* .. */ ];

for(let i = 0; i < options.length; ++i) {
  suite.add(`Thing ${options[i]}`, () => { /* .. */ });
}

suite.run();
```

With the new CLI-only approach and the current benchmark resolution (named `function` exports starting with `$` and default `function` export) strategy it's not possible to do this.

Does anyone have any idea how to bring this feature back?

**Comment by yamiteru** [comment]
## Generating benchmarks

When it comes to generating benchmarks I think our safest bet is to do something like this:

```ts
const options = [ /* .. */ ];
const $$benchmarks = {};

for(const option of options) {
  $$benchmarks[`Thing ${option}`] = () => { /* .. */ };
}

export default {
  $$benchmarks
};
```

## Benchmark events

Also right now we don't support benchmark events so I think we should bring them back like this:

- Default function export
```ts
export const $$onBenchmarkStart = () => { /* .. */ };
export const $$onBenchmarkEnd = () => { /* .. */ };

export default () => { /* .. */ };
```

- Default object export
```ts
export default {
  $$benchmark: () => { /* .. */ },
  $$onBenchmarkStart: () => { /* .. */ },
  $$onBenchmarkEnd: () => { /* .. */ }
};
```

- Named object export
```ts
export const $forEach = {
  $$benchmark: () => { /* .. */ },
  $$onBenchmarkStart: () => { /* .. */ },
  $$onBenchmarkEnd: () => { /* .. */ }
};
```

- Named function export
```ts
export const $$benchmark = () => { /* .. */ };
export const $$onBenchmarkStart = () => { /* .. */ };
export const $$onBenchmarkEnd = () => { /* .. */ };
```

## Suite

I kind of got rid of suite as a concept since a suite is just a bunch of benchmarks grouped together. I think I should treat any context with multiple benchmarks as a suite (folder with default function export files, file with named function exports, etc.).

In the case where one file has many benchmarks it's very straightforward:

- Default object export
```ts
export default {
  $$name: "Test suite",
  $$benchmarks: { /* .. */ },
  $$setup: () => { /* .. */ },
  $$onTeardown: () => { /* .. */ }
};
```

- Named function export
```ts
export const $$name = "Test suite";

export const $forEach = () => { /* .. */ };
export const $forOf = () => { /* .. */ };
export const $while = () => { /* .. */ };
export const $for = () => { /* .. */ };

export const $$setup = () => { /* .. */ };
export const $$onTeardown = () => { /* .. */ };
```

But I'm not sure how to implement this with a folder acting as a suite. 

Maybe we could have a file called `$config.js` which would use named exports or default object export to define all suite config.

Also I'm not sure what to do if we define suite in a folder with the `$config.js` file but we add a file containing a suite in the same folder. Is it a suite in a suite? If yes then how should that work?

Conceptually speaking I don't have a problem with variable suite/benchmark structure depth. It'd look similarly to Jest with many nested `describe`/`test`/`it` functions.

I'm thinking that we want a suite basically only for creating shared data with `setup`. Other than that suite just groups benchmarks which we've already accomplished with files and folders. The same applies to suite name which is now either file or folder name or it's specified with `$$name`.

So I'm thinking that we might create shared data by literally just creating a variable which we can then use in the benchmarks. Thanks to this we'll have correct types of the data which might have been impossible with just an exported function like `$$setup`. We can then reset or manipulate the shared data in the benchmark events.

I think this is a good solution but I'd be happy for any feedback on this.

**Comment by H4ad** [comment]
Did you already deploy the CLI functionality? 

I install the latest version but I could not figure out how to make it work.
The package.json says it calls `./dist/index.js` but inside the installation folder it only have `.cjs` and `.mjs` files.

**Comment by yamiteru** [comment]
Hey yeah it's not released yet. You'd have to clone the repo and run build it yourself. I have big plans with this library and releasing it now when I change most of the code with every MR would kinda be pointless.

**Comment by yamiteru** [comment]
I'm currently working with a professional theoretical statistician to return meaningful and sound statistics from the benchmarks. Until then the CLI version basically just saves thousands of iteration measurements into a binary file and it's up to you what you do with it.
